// Code generated by mockery v2. DO NOT EDIT.

package mocks

import (
	io "io"
	mock "github.com/stretchr/testify/mock"
)

type MockS3Client struct {
	mock.Mock
}

func (m *MockS3Client) UploadFile(bucketName, key string, file io.Reader) (string, error) {
	ret := m.Called(bucketName, key, file)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string, io.Reader) string); ok {
		r0 = rf(bucketName, key, file)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, io.Reader) error); ok {
		r1 = rf(bucketName, key, file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

