version: "3.8"

services:
  db:
    image: postgres:15
    container_name: todo_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566" # LocalStack gateway (SQS, S3, etc.)
    environment:
      SERVICES: "s3,sqs"
      DOCKER_HOST: "unix:///var/run/docker.sock"
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_service
    depends_on:
      - db
      - localstack
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: todo_db
      SQS_ENDPOINT: http://localstack:4566
      S3_ENDPOINT: http://localstack:4566
      S3_BUCKET: todo-bucket
      SQS_QUEUE: todo-queue
      AWS_REGION: us-east-1
    command: ["make", "run"]

volumes:
  postgres_data:
  localstack_data:

